package colegio.vista;
import colegio.*;

public class FrameColegio extends javax.swing.JFrame {
    public Colegio escuela;
    /**
     * Creates new form Colegio
     * @param c
     */
    public FrameColegio(Colegio c) {
        initComponents();
        this.escuela = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio0 = new javax.swing.JDesktopPane();
        Titulo0 = new javax.swing.JLabel();
        Menu0 = new javax.swing.JMenuBar();
        AñadirEstudiante = new javax.swing.JMenu();
        AñadirMateria = new javax.swing.JMenu();
        Inscribir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        Titulo0.setText("Bienvenido a la Escuela");

        Escritorio0.setLayer(Titulo0, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Escritorio0Layout = new javax.swing.GroupLayout(Escritorio0);
        Escritorio0.setLayout(Escritorio0Layout);
        Escritorio0Layout.setHorizontalGroup(
            Escritorio0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Escritorio0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo0)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        Escritorio0Layout.setVerticalGroup(
            Escritorio0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Escritorio0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo0)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        AñadirEstudiante.setText("Añadir Estudiante");
        AñadirEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirEstudianteMouseClicked(evt);
            }
        });
        Menu0.add(AñadirEstudiante);

        AñadirMateria.setText("Añadir Materia");
        AñadirMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirMateriaMouseClicked(evt);
            }
        });
        Menu0.add(AñadirMateria);

        Inscribir.setText("Inscribir Estudiante");
        Inscribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InscribirMouseClicked(evt);
            }
        });
        Menu0.add(Inscribir);

        setJMenuBar(Menu0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Escritorio0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Escritorio0, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirEstudianteMouseClicked
        AddEstudiante ae0 = new AddEstudiante (escuela);
        ae0.setVisible(true);
        Escritorio0.add(ae0);
        Escritorio0.moveToFront(ae0);
    }//GEN-LAST:event_AñadirEstudianteMouseClicked

    private void AñadirMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirMateriaMouseClicked
        AddMateria am0 = new AddMateria (escuela);
        am0.setVisible(true);
        Escritorio0.add(am0);
        Escritorio0.moveToFront(am0);
    }//GEN-LAST:event_AñadirMateriaMouseClicked

    private void InscribirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InscribirMouseClicked
        InscribirEstudiante ie0 = new InscribirEstudiante (escuela);
        ie0.setVisible(true);
        Escritorio0.add(ie0);
        Escritorio0.moveToFront(ie0);
    }//GEN-LAST:event_InscribirMouseClicked

    /**
     * @param args the command line arguments
     * @param c
     */
    public static void main(Colegio c, String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameColegio(c).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AñadirEstudiante;
    private javax.swing.JMenu AñadirMateria;
    private javax.swing.JDesktopPane Escritorio0;
    private javax.swing.JMenu Inscribir;
    private javax.swing.JMenuBar Menu0;
    private javax.swing.JLabel Titulo0;
    // End of variables declaration//GEN-END:variables
}
