package colegio.vista;
import colegio.*;
import java.util.Iterator;

public class InscribirEstudiante extends javax.swing.JInternalFrame {
    public Colegio escuela;
    /**
     * Creates new form InscribirEstudiante
     * @param c
     */
    public InscribirEstudiante(Colegio c) {
        this.escuela = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title0 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        InputEstudiante = new javax.swing.JComboBox<Alumno>();
        Title2 = new javax.swing.JLabel();
        InputMateria = new javax.swing.JComboBox<Materia>();
        Inscribir = new javax.swing.JButton();
        Out0 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(500, 250));

        Title0.setText("Inscribir Estudiante");

        Title1.setText("Estudiante:");

        Iterator <Alumno> it0 = this.escuela.estudiantes.iterator();
        InputEstudiante.setModel(new javax.swing.DefaultComboBoxModel<Alumno> ());
        while (it0.hasNext()) {
            InputEstudiante.addItem (it0.next());
        }

        Title2.setText("Materia:");

        Iterator <Materia> it1 = this.escuela.materias.iterator();
        InputMateria.setModel(new javax.swing.DefaultComboBoxModel<Materia>());
        while (it1.hasNext()) {
            InputMateria.addItem(it1.next());
        }

        Inscribir.setText("Inscribir");
        Inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title1)
                            .addComponent(Title2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputEstudiante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 193, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Out0)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(146, Short.MAX_VALUE)
                    .addComponent(Title0)
                    .addContainerGap(146, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title1)
                    .addComponent(InputEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inscribir)
                .addGap(18, 18, 18)
                .addComponent(Out0)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Title0)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void InscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribirActionPerformed
        Alumno temp0 = InputEstudiante.getItemAt(InputEstudiante.getSelectedIndex());
        Materia temp1 = InputMateria.getItemAt(InputMateria.getSelectedIndex());
        
        if (temp0.listaMaterias.contains(temp1)) {
            Out0.setText("Entrada inválida: " + temp0 + " ya está inscripto en ésa materia.");
        }
        else {
            temp0.agregarMateria (temp1);
            Out0.setText(temp0.getNombre() + " fue inscripto a " + temp1.getNombre());
            System.out.println(temp0 + " está inscripto en: " + temp0.getMaterias());
        }
    }//GEN-LAST:event_InscribirActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> InputEstudiante;
    private javax.swing.JComboBox<Materia> InputMateria;
    private javax.swing.JButton Inscribir;
    private javax.swing.JLabel Out0;
    private javax.swing.JLabel Title0;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    // End of variables declaration//GEN-END:variables
}
